- name: prefetch containers
  shell: docker pull as65342/{{ item }}:{{ version }}
  with_items:
    - mariadb
    - mariadb-client
  tags:
  - mariadb

- name: add group
  group:
    name: mysql
    gid: "{{ uidgid }}"
  tags:
  - mariadb

- name: add user
  user:
    name: mysql
    uid: "{{ uidgid }}"
    group: mysql
    home: /var/empty
    shell: /sbin/nologin
    password: !
    comment: MariaDB system account
  tags:
    - mariadb

- name: create configuration directory
  file:
    dest: "/etc/mysql"
    state: directory
    owner: root
    group: mysql
    mode: 0750
  tags:
    - mariadb

- name: install configuration file
  copy:
    src: my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    group: mysql
    mode: 0640
  notify:
    - restart mariadb
  tags:
    - mariadb

- name: create database directory
  file:
    dest: /var/lib/mysql
    state: directory
    owner: root
    group: mysql
    mode: 0770
  tags:
    - mariadb

- name: install wrapper scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - mysql
    - mysqladmin
    - mysqldump
    - mysqlimport
  tags:
    - mariadb

- name: install unit file
  template:
    src: mariadb.service.j2
    dest: /etc/systemd/system/mariadb.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mariadb
  tags:
    - mariadb

- name: enable service
  systemd:
    name: mariadb
    enabled: yes
    state: started
    daemon_reload: true
  tags:
    - mariadb

- name: install version fact
  copy:
    content: '{"version":"{{ version }}"}'
    dest: /etc/ansible/facts.d/mariadb.fact
    owner: root
    group: root
    mode: 0644
  tags:
    - mariadb