#!/bin/sh

# Generate configuration
echo '[+] Pulling configuration'
until confd -onetime -node ${ETCD_ENDPOINTS}; do
  echo "[+] Waiting for etcd to become available"
  sleep 5
done

confd -node ${ETCD_ENDPOINTS} &
echo '[+] Watching for configuration changes'

echo '[+] Starting dhcpd'
exec /usr/sbin/dhcpd -f eth0
