#!/bin/bash

if [[ $(whoami) != 'root' ]]; then
  echo "[E] Starting a container requires root rights"
  exit 1
fi

rkt run --interactive metasploit --memory 2G -- ${@}
cleanup_rkt_containers.sh metasploit
