#!/bin/sh

ETCDCTL='/usr/bin/etcdctl'
ETCDCTL_ENDPOINTS='10.42.16.252:2379'
ETCDCTL_API=3
BASE='/unbound'

UNBOUND_CONF='/etc/unbound/unbound.conf'
NEWCONF='/etc/unbound/unbound.conf.new'

# Do we use dynamic configuration at all?
if [[ -z "${ETCDCTL_ENDPOINTS}" ]]; then
  echo "[W] ETCDCTL_ENDPOINTS not defined"
  exit 0
fi

# Check if unbound directory is configured
${ETCDCTL} get ${BASE} >/dev/null
if [[ ${?} -ne 0 ]]; then
  echo "[W] No unbound settings found under etcd"
  exit 0
fi

echo -n "[+] Generating unbound.conf: "

rm -f ${NEWCONF}

cat > ${NEWCONF} <<EOF
server:
  verbosity: 0
  statistics-interval: 0
  statistics-cumulative: no
  extended-statistics: yes
  do-daemonize: no
  username: "unbound"
  logfile: ""
  use-syslog: no
  root-hints: /etc/unbound/root.hints
  auto-trust-anchor-file: /etc/unbound/root.key
EOF

${ETCDCTL} get --prefix ${BASE} --keys-only | egrep -v "${BASE}/forward_zone/|${BASE}/access_control/|^$" | while read ETCD_KEY; do
  KEY="$(echo ${ETCD_KEY} | sed -e "s,${BASE}/,,g")"

  case "${KEY}" in
    "identity"|"version")
      VALUE="$(${ETCDCTL} get ${ETCD_KEY} | tail -1)"
      if [[ -z "${VALUE}" ]]; then
        continue
      fi
      echo "  ${KEY}: ${VALUE}" >> ${NEWCONF}
      ;;
    "target-fetch-policy")
      VALUE="$(${ETCDCTL} get ${ETCD_KEY} | tail -1)"
      echo "  ${KEY}: \"${VALUE}\"" >> ${NEWCONF}
      ;;
    "ip-address")
      VALUE="$(${ETCDCTL} get ${ETCD_KEY} | tail -1)"
      echo ${VALUE} | sed -e 's/,/\n/g' | while read IP; do
        echo "  ${KEY}: ${IP}" >> ${NEWCONF}
      done
      ;;
    "forward_zone"):
      continue
      ;;
    *)
      VALUE="$(${ETCDCTL} get ${ETCD_KEY} | tail -1)"
      echo "  ${KEY}: ${VALUE}" >> ${NEWCONF}
      ;;
  esac
done

${ETCDCTL} get --prefix ${BASE}/access_control --keys-only | egrep -v "^$" | while read ETCD_KEY; do
  NETWORK="$(echo ${ETCD_KEY} | sed -e "s,${BASE}/access_control/,,g")"
  KEY="$(echo ${NETWORK} | sed -e 's,_,/,g')"

  VALUE="$(${ETCDCTL} get --prefix ${ETCD_KEY} | tail -1)"
  echo "  access-control: ${KEY} ${VALUE}" >> ${NEWCONF}
done

cat >>${NEWCONF} <<EOF

remote-control:
  control-enable: yes
  control-use-cert: yes
  control-port: 8953
  server-key-file: "/etc/unbound/unbound_server.key"
  server-cert-file: "/etc/unbound/unbound_server.pem"
  control-key-file: "/etc/unbound/unbound_control.key"
  control-cert-file: "/etc/unbound/unbound_control.pem"
EOF

${ETCDCTL} get --prefix ${BASE}/forward_zone --keys-only | egrep -v "^$" | while read ETCD_ZONE_KEY; do
  NAME="$(echo ${ETCD_ZONE_KEY} | sed -e "s,${BASE}/forward_zone/,,g")"
  ADDR="$(${ETCDCTL} get ${ETCD_ZONE_KEY} | tail -1)"
  cat >> ${NEWCONF} <<EOF

forward-zone:
  name: "${NAME}"
  forward-addr: "${ADDR}"
EOF
done

echo "done"

unbound-checkconf ${NEWCONF} && mv -v ${NEWCONF} ${UNBOUND_CONF}
