#!/bin/sh

# Add ipv6 address
if [[ ! -z "${IP6_UNBOUND}" ]]; then
  echo "[+] Adding ${IP6_NSD} to container"
  ip -6 addr add ${IP6_UNBOUND}/64 dev eth0
  ip -6 route add default via ${IP6_DEFAULT_GW}
fi

# Fix permissions on /etc/unbound dir
install -d -o root -g unbound -m 0770 /etc/unbound

# Update root.key
echo '[+] Updating root.key'
unbound-anchor -a /etc/unbound/root.key -v

# Generate unbound-control keys if needed
echo '[+] Generating control keys'
unbound-control-setup

# Generate configuration
echo '[+] Pulling configuration'
until confd -onetime -node ${ETCD_ENDPOINTS}; do
  echo "[+] Waiting for etcd to become available"
  sleep 5
done

confd -node ${ETCD_ENDPOINTS} &
echo '[+] Watching for configuration changes'

# Anycast support
echo '[+] Starting anycast agent'
/usr/sbin/anycast-agent -name dns &

# Metrics support
echo '[+] Starting metrics agent'
/usr/bin/unbound_exporter &

echo '[+] Starting unbound'
exec /usr/sbin/unbound
