#!/bin/sh

# Fix permissions on /etc/unbound dir
install -d -o root -g unbound -m 0770 /etc/unbound

# Update root.key
unbound-anchor -a /etc/unbound/root.key -v

# Generate unbound-control keys if needed
unbound-control-setup

# Generate configuration
genconfig

# Gather metrics
(sleep 3 ; gather_metrics) &

exec /usr/sbin/unbound
