- name: prefetch container
  shell: docker pull as65342/dovecot:{{ version }}
  tags:
    - dovecot

- name: add group
  group:
    name: dovecot
    gid: "{{ uidgid }}"
  tags:
    - dovecot

- name: add user
  user:
    name: dovecot
    uid: "{{ uidgid }}"
    group: dovecot
    groups: tls
    home: /var/empty
    shell: /sbin/nologin
    password: !
    comment: Dovecot system account
  tags:
    - dovecot

- name: create configuration directories
  file:
    dest: "/etc/{{ item }}"
    state: directory
    owner: root
    group: dovecot
    mode: 0750
  with_items:
    - dovecot
    - dovecot/conf.d
  tags:
    - dovecot

- name: install static configuration files
  copy:
    src: conf.d/
    dest: /etc/dovecot/conf.d
  tags:
    - dovecot

- name: install dynamic configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/dovecot/{{ item }}"
    owner: root
    group: dovecot
    mode: 0640
  with_items:
    - dovecot.conf
    - dovecot-dict-auth.conf.ext
    - dovecot-ldap.conf.ext
  tags:
    - dovecot

- name: create database directory
  file:
    dest: /var/lib/dovecot
    state: directory
    owner: root
    group: dovecot
    mode: 0770
  tags:
    - dovecot

- name: create certificate directory
  file:
    dest: /etc/certs/dovecot
    state: directory
    owner: root
    group: dovecot
    mode: 0750
  tags:
  - dovecot

- name: install certificate configuration
  template:
    src: config.json.j2
    dest: /etc/certs/dovecot/config.json
    owner: root
    group: ldap
    mode: 0640
  tags:
  - dovecot

- name: check if certificate is installed
  shell: "stat /etc/certs/dovecot/dovecot.pem"
  register: certs
  ignore_errors: true
  tags:
  - dovecot

- name: fetch new certificates
  shell: "/usr/local/bin/fetch_certs dovecot"
  when: certs is failed
  tags:
  - dovecot

- name: fix permissions for new certs
  shell: "find /etc/certs/dovecot/dovecot* -type f -exec chmod 0640 {} \\;"
  when: certs is failed
  tags:
  - dovecot

- name: fix ownership for new certs
  shell: "find /etc/certs/dovecot/dovecot* -type f -exec chown root:ldap {} \\;"
  when: certs is failed
  tags:
  - dovecot

- name: install ca bundle
  shell: "install -o root -g ldap -m 0640 /etc/cfssl/ca-bundle.pem /etc/certs/dovecot/ca-bundle.pem"
  when: certs is failed
  tags:
  - dovecot

- name: install unit file
  template:
    src: dovecot.service.j2
    dest: /etc/systemd/system/dovecot.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dovecot
  tags:
    - dovecot

- name: enable service
  systemd:
    name: dovecot
    enabled: yes
    state: started
    daemon_reload: yes
  tags:
    - dovecot

- name: install version fact
  copy:
    content: '{"version":"{{ version }}"}'
    dest: /etc/ansible/facts.d/dovecot.fact
    owner: root
    group: root
    mode: 0644
  tags:
    - dovecot