#!/bin/sh

PGDATA='/var/lib/postgresql/9.5'
PGLOG='/var/lib/postgresql/9.5/postmaster.log'
PGUSER='postgres'
PGGROUP='postgres'
SQL_FILES='/sql'

# Initialize the database first
if [[ ! -d "${PGDATA}" ]]; then
  mkdir -p "${PGDATA}"
  chown -Rf ${PGUSER}:${PGGROUP} ${PGDATA}
  chmod 0700 ${PGDATA}
  su - ${PGUSER} -c "initdb --pgdata \"${PGDATA}/data\""

  # Check if we have the sql initialization directory
  if [[ ! -d ${SQL_FILES} ]]; then
    echo "[E] ${SQL_FILES} not found"
    exit 1
  fi

  # Startup database once and load all sql files
  su - ${PGUSER} -c "pg_ctl -D \"${PGDATA}/data\" start -s -w -l ${PGLOG}"
  ls ${SQL_FILES}/*.sql | while read SQL_FILE; do
    echo "[*] Loading ${SQL_FILE}"
    su - ${PGUSER} -c "psql -f \"${SQL_FILE}\""
  done

  # Shutdown database
  su - ${PGUSER} -c "pg_ctl -D \"${PGDATA}/data\" stop"

  # Update pg_hba.conf so containers can connect
  echo -e "host\tall\tall\tsamenet\t\t\t\tmd5" >> ${PGDATA}/data/pg_hba.conf
fi

# Start up postgresql
su - ${PGUSER} -c "exec postgres -D \"${PGDATA}/data\" -i -h 0.0.0.0"
