#!/bin/sh

USERLIST='/root/userlist.txt'

# Add erlang to the path
PATH="${PATH}:/opt/erlang/bin"
export PATH

RABBITMQCTL='/opt/rabbitmq/sbin/rabbitmqctl'

if [[ ! -f "${USERLIST}" ]]; then
  echo "[E] ${USERLIST} not found, nothing to do"
  exit 1
fi

# Start up rabbitmq in the background so we can add users
/opt/rabbitmq/sbin/rabbitmq-server -detached
sleep 3
${RABBITMQCTL} node_health_check || exit 1

cat ${USERLIST} | while read LINE; do
  USER="$(echo ${LINE} | cut -d\: -f1)"
  PASS="$(echo ${LINE} | cut -d\: -f2)"
  EXCHANGE="$(echo ${LINE} | cut -d\: -f3)"

  ${RABBITMQCTL} list_users | grep -q "${USER}"
  if [[ ${?} -eq 1 ]]; then
    ${RABBITMQCTL} add_user "${USER}" "${PASS}"
  fi

  ${RABBITMQCTL} list_user_permissions "${USER}" \
    | grep -v '^Listing' | grep -q "${EXCHANGE}"
  if [[ ${?} -eq 1 ]]; then
    ${RABBITMQCTL} set_permissions "${USER}" "${EXCHANGE}" '.*' '.*'
  fi
done

# Shutdown the rabbitmq server running in the background so we can
# start up a rabbitmq server in the foreground
pkill epmd
pkill beam.smp
sleep 1
