#!/bin/sh

# Generate configuration
genconfig

# Generate unbound-control keys if needed
nsd-control-setup

# Gather metrics
(sleep 3 ; gather_metrics) &

echo '[+] Starting nsd'
exec /usr/sbin/nsd -d
