#!/bin/sh

PLUGINS="grafana-piechart-panel savantly-heatmap-panel"
PLUGIN_DIR='/opt/grafana/data/plugins'

GF_PLUGIN_DIR="${PLUGIN_DIR}"
export GF_PLUGIN_DIR

if [[ ! -d "${PLUGIN_DIR}" ]]; then
  mkdir -p "${PLUGIN_DIR}"
fi

# Install plugins
for PLUGIN in ${PLUGINS}; do
  if [[ ! -d "${PLUGIN_DIR}/${PLUGIN}" ]]; then
    echo "[+] Installing ${PLUGIN}"
    /opt/grafana/bin/grafana-cli plugins install ${PLUGIN}
  fi
done

cd /opt/grafana
exec /opt/grafana/bin/grafana-server
