#!/bin/sh

echo '[+] Pulling configuration'
until confd -onetime -node ${ETCD_ENDPOINTS}; do
  echo "[+] Waiting for etcd to become available"
  sleep 5
done

confd -node ${ETCD_ENDPOINTS} &
echo '[+] Watching for configuration changes'

echo '[+] Starting prometheus'
cd /opt/prometheus
exec /opt/prometheus/prometheus
