#!/bin/sh

set -x

DATA_DIR='/var/lib/openldap'

if [[ ! -f "${DATA_DIR}/__db.001" ]]; then
  echo '[+] Initializing directory'
  slapadd -v -l /etc/openldap/initdb.ldif
  chown -R ldap:ldap ${DATA_DIR}/*
  chown root:ldap ${DATA_DIR}/DB_CONFIG
  rm -f /etc/openldap/initdb.ldif
fi


exec /usr/sbin/slapd -h "ldaps:///" \
    -u ldap -g ldap -f /etc/openldap/slapd.conf \
    -d1
