#!/bin/sh

set -x

GRAPHITE_HOME='/opt/graphite'
GRAPHITE_STORAGE="${GRAPHITE_HOME}/storage"
WEB_LOGS="${GRAPHITE_STORAGE}/log"

install -d -o root -g graphite -m 0770 ${GRAPHITE_STORAGE}

if [[ ! -d "${GRAPHITE_STORAGE}/whisper" ]]; then
  install -d -o root -g graphite -m 0770 ${GRAPHITE_STORAGE}/whisper
fi

if [[ ! -d "${GRAPHITE_STORAGE}/rrd" ]]; then
  install -d -o root -g graphite -m 0770 ${GRAPHITE_STORAGE}/rrd
fi

if [[ ! -f "${GRAPHITE_STORAGE}/index" ]]; then
  install -o root -g graphite -m 0770 /dev/null ${GRAPHITE_STORAGE}/index
fi

if [[ ! -d "${WEB_LOGS}/webapp" ]]; then
  install -d -o root -g graphite -m 0770 ${WEB_LOGS}/webapp
fi

if [[ ! -f "${GRAPHITE_STORAGE}/graphite.db" ]]; then
  echo "[+] Creating django database"
  cd /opt/graphite/webapp/graphite
  python manage.py syncdb --noinput
  chown graphite:graphite ${GRAPHITE_STORAGE}/graphite.db
fi

exec /usr/sbin/uwsgi --emperor /etc/uwsgi
