#!/bin/sh

set -e

CFSSL_DIR='/etc/cfssl'
cd ${CFSSL_DIR}

find ${CFSSL_DIR} -type d -maxdepth 1 -mindepth 1 | while read DIRNAME; do
  echo "[+] Generating key for ${SERVICE}"
  SERVICE="$(basename ${DIRNAME})"
  cd ${DIRNAME}
  cfssl genkey config.json | cfssljson -bare ${SERVICE}
  cfssl sign -remote pki.as65342.net:8888 -profile "server" \
    ${SERVICE}.csr | cfssljson -bare ${SERVICE}
  chown root:ldap ${SERVICE}-key.pem
  chmod 0640 ${SERVICE}-key.pem
done
