#!/bin/bash

if [[ $(whoami) != 'root' ]]; then
  echo '[E] Starting a container requires root rights'
  exit 1
fi

if [[ ${#} -lt 1 ]]; then
  echo "Usage: $(basename ${0}) <container>"
  exit 1
fi
CONTAINER="${1}"
shift

source /etc/rkt-environment

rkt-cleanup ${CONTAINER}
rkt run \
  --dns ${IP_UNBOUND} \
  --dns-search "${DOMAIN}" \
  --interactive ${CONTAINER} \
  --set-env-file /etc/rkt-environment \
  ${@} \
  --caps-retain=CAP_NET_ADMIN,CAP_NET_BIND_SERVICE,CAP_SYS_CHROOT,CAP_CHOWN,CAP_SETGID,CAP_SETUID
rkt-cleanup ${CONTAINER}
