#!/bin/sh

if [[ ${#} -ne 1 ]]; then
  echo "Usage: $(basename ${0}) <container>"
  exit 1
fi
NAME="${1}"

ID="$(rkt list | grep 'running' | grep ${NAME} | awk '{print $1}')"
if [[ -z "${ID}" ]]; then
  echo "[E] Did not find any running container for ${NAME}"
  exit 1
fi

rkt enter ${ID} /bin/sh
