#!/bin/sh

if [[ -z "${ETCDCTL_ENDPOINTS}" ]]; then
  echo "[E] ETCDCTL_ENDPOINTS not set"
  exit 1
fi

ETCDCTL="$(dirname $(readlink -f ${0}))/etcdctl"

if [[ ! -x "${ETCDCTL}" ]]; then
  echo "[E] etcdctl not found"
  exit 1
fi

if [[ ${#} -ne 2 ]]; then
  echo "[E] Usage: $(basename ${0}) <basedir> <settings file>"
  echo "    Set CLEAR_BASEDIR to clear directory"
  exit 1
fi
BASEDIR="${1}"
SETTINGS_FILE="${2}"

if [[ ! -f "${SETTINGS_FILE}" ]]; then
  echo "[E] ${SETTINGS_FILE} not found"
  exit 1
fi

if [[ ! -z "${CLEAR_BASEDIR}" ]]; then
  ${ETCDCTL} del -r ${BASEDIR}
fi

cat ${SETTINGS_FILE} | while read SETTING; do
  KEY="$(echo ${SETTING} | cut -d= -f1)"
  VALUE="$(echo ${SETTING} | cut -d= -f2-)"

  echo -n "${BASEDIR}/${KEY} -> "
  #${ETCDCTL} put ${BASEDIR}/${KEY} "${VALUE}"
  curl -L -X PUT ${ETCD_ENDPOINTS}/v2/keys${BASEDIR}/${KEY} \
    -d value="${VALUE}" >/dev/null 2>&1 && echo "ok" || echo "FAILED"
done
